flight_06_jpa_jsf/src/main/java/entity/Flight.java
package entity;

import javax.annotation.Generated;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Flight {
	
	@Id
    @GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
	private String flightNumber;
	private String fromAirport; // from is a SQL keyword and therefore can not be used!
	private String toAirport;

	public Flight() {
	}

	public Flight(String flightNumber, String fromAirport, String toAirport) {
		this.flightNumber = flightNumber;
		this.fromAirport = fromAirport;
		this.toAirport = toAirport;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getFlightNumber() {
		return flightNumber;
	}

	public void setFlightNumber(String flightNumber) {
		this.flightNumber = flightNumber;
	}

	public String getFromAirport() {
		return fromAirport;
	}

	public void setFromAirport(String fromAirport) {
		this.fromAirport = fromAirport;
	}

	public String getToAirport() {
		return toAirport;
	}

	public void setToAirport(String toAirport) {
		this.toAirport = toAirport;
	}

	@Override
	public String toString() {
		return "Flight [id=" + id + ", flightNumber=" + flightNumber + ", fromAirport=" + fromAirport + ", toAirport="
				+ toAirport + "]";
	}


}

flight_06_jpa_jsf/src/main/java/controller/FlightsController.java
package controller;

import java.util.List;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import ejb.FlightService;
import entity.Flight;

@ManagedBean
@SessionScoped
public class FlightsController {

	@EJB
	FlightService flightService;

	private Flight currentFlight = new Flight();

	public String getHello() {
		return "Hallo world";
	}

	public Flight getCurrentFlight() {
		return currentFlight;
	}

	public void setCurrentFlight(Flight currentFlight) {
		this.currentFlight = currentFlight;
	}

	public String create() {
		flightService.addFlight(currentFlight);
		currentFlight = new Flight();
		return "flights";
	}

	public List<Flight> getFlights() {
		return flightService.getFlights();
	}

	public void remove(Flight flight) {
		flightService.removeFlight(flight.getId());
	}
}

flight_06_jpa_jsf/src/main/java/web/FlightServlet.java
package web;

import java.io.IOException;
import java.io.Writer;

import javax.ejb.EJB;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import ejb.FlightService;
import entity.Flight;

@WebServlet("/flights")
public class FlightServlet extends HttpServlet {

	@EJB
	private FlightService flightService;

	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		Writer writer = response.getWriter();
		writer.append("<html>");
		writer.append(flightService.helloWorld()).append(", Served at: ").append(request.getContextPath());

		String id;
		if (request.getParameter("add") != null) {
			Flight flight = new Flight();
			flight.setFlightNumber("OS1234");
			flight.setFromAirport("A");
			flight.setToAirport("B");
			flightService.addFlight(flight);
			writer.append("<p>added: " + flight);
			writer.append("</p>");
		} else if ((id = request.getParameter("remove")) != null) {
			flightService.removeFlight(Integer.parseInt(id));
			writer.append("<p>removed</p>");
		} else {
			writer.append("<ul>");
			writer.append("<ul>");
			for (Flight flight : flightService.getFlights()) {
				writer.append("<li>");
				writer.append(flight.getFlightNumber());
			}
			writer.append("</ul>");
		}
		writer.append("</html>");
	}

}

flight_06_jpa_jsf/src/main/webapp/create.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
	<title>Create Flight</title>
</h:head>
<h:body>
	<p>Create Flight</p>
	<h:form>
		<h:panelGrid columns="2">
			<h:outputLabel value="Flight number" for="flightNumber" />
			<h:inputText id="flightNumber"
				value="#{flightsController.currentFlight.flightNumber}"
				title="flightNumber" />
			<h:outputLabel value="From" for="from" />
			<h:inputText id="from"
				value="#{flightsController.currentFlight.fromAirport}" title="from" />
			<h:outputLabel value="To" for="to" />
			<h:inputText id="to" value="#{flightsController.currentFlight.toAirport}"
				title="to" />
		</h:panelGrid>
		<h:commandLink action="#{flightsController.create}" value="Create" />
	</h:form>
</h:body>
</html>

flight_06_jpa_jsf/src/main/webapp/flights.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
	<title>Flights</title>
</h:head>
<h:body>
	<p>Hello from Facelets</p>
	<p>
		<h:outputText value="#{flightsController.hello}" />
	</p>
	<p>
		<h:button value="Create Flight" outcome="create" />
	</p>
	<h:form>
		<h:dataTable value="#{flightsController.flights}" var="flight">
			<h:column>
				<f:facet name="header">
					<h:outputText value="id" />
				</f:facet>
				<h:outputText value="#{flight.id}" />
			</h:column>
			<h:column>
				<f:facet name="header">
					<h:outputText value="flight number" />
				</f:facet>
				<h:outputText value="#{flight.flightNumber}" />
			</h:column>
			<h:column>
				<f:facet name="header">
					<h:outputText value="from" />
				</f:facet>
				<h:outputText value="#{flight.fromAirport}" />
			</h:column>
			<h:column>
				<f:facet name="header">
					<h:outputText value="to" />
				</f:facet>
				<h:outputText value="#{flight.toAirport}" />
			</h:column>
			<h:column>
				<h:commandLink value="Remove"
					action="#{flightsController.remove(flight)}" />
			</h:column>
		</h:dataTable>
	</h:form>
</h:body>
</html>